[package]
name = "ec-linear"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true, features = ["alloc"] }

ec-core = { workspace = true }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[lints]
workspace = true
