[package]
name = "ec-core"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
itertools = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true, features = ["alloc"] }
rayon = "1.7.0"
macro_railroad_annotation = { workspace = true }

[dev-dependencies]
rand = { workspace = true, features = ["alloc", "small_rng"] }

[lints]
workspace = true

